#!/bin/bash

# This is a modified version of
# https://github.com/tashrifsanil/Gentoo-Install-Scripts

# -------------------------
# Notes to self about usage
# -------------------------
# Before running:
#  * Make the required partitions
#  * Check internet connection
#  * 
# 
# After running:
#  * Change root password 
#


LRED='\033[01;31m'
GREEN='\033[0;32m'
LCYAN='\033[1;36m'
LBLUE='\033[1;34m'
LPURPLE='\033[0;35m'
DGRAY='\033[1;30m'
NC='\033[0m' # No Color

MOUNT_LOCATION=/mnt/gentoo
TIMEZONE=Europe/Helsinki

CFLAGS="-march=znver2 -O2 -pipe"
USE_FLAGS="-suid -systemd X alsa pulseaudio elogind"
MAKE_OPTIONS="-j6"

BIOS_PARTITION=/dev/nvme0n1p6
BOOT_PARTITION=/dev/nvme0n1p7
SWAP_PARTITION=/dev/nvme0n1p8
ROOT_PARTITION=/dev/nvme0n1p9

ROOT_FS_TYPE=ext4

STAGE3=stage3* # Have the stage3 in the same folder as this script
KERNEL_CONFIG_FILE=$(pwd)/.config # Have the kernel config in the same folder as this script

HOSTNAME="amichan"

PACKAGES="lzop app-arch/lz4 sys-fs/e2fsprogs sys-fs/dosfstools sys-fs/ntfs3g net-wireless/wpa_supplicant net-wireless/wireless-tools net-misc/dhcpcd app-text/tree sys-apps/pciutils"
TOOLS=""

message ()
{
  echo
  echo -e " $LBLUE>>> $LRED $@ $NC"
}

command ()
{
  echo -e "$LCYAN$@$NC"
  $@
  if [ $? -ne 0 ]; then
    echo -e "$LREDFailed$NC"
    exit 1
  fi
}

install_gentoo_prep ()
{
  # Disk Setup
  message "Beginning Installation Process"
  message "Formating Boot Partition"
  command mkfs.fat -F 32 $BOOT_PARTITION
  message "Formating Swap Partition"
  command mkswap $SWAP_PARTITION
  command swapon $SWAP_PARTITION
  message "Formating Root Partition"
  command mkfs.${ROOT_FS_TYPE} $ROOT_PARTITION

  # Mount Disks
  message "Mounting Root and Boot partitions"
  command mount -v $ROOT_PARTITION $MOUNT_LOCATION
  command mkdir -pv ${MOUNT_LOCATION}/boot/efi
  command mount -v $BOOT_PARTITION ${MOUNT_LOCATION}/boot/efi

  message "Make sure that date and time is set correctly, if it isn't then it can cause problems in the future"
  command date
  message "Is the following date correct (y/n)?"
  read DATE_CORRECT
  if [ $DATE_CORRECT = "n" ]; then
    message "Enter the date and time in MMDDhhmmYYYY format"
    read CORRECTED_DATE
    command date $CORRECTED_DATE
  fi

  # Stage3 Tarball
  message "Copying stage3 tarball to system"
  command cp -rv $STAGE3 $MOUNT_LOCATION
  command cd $MOUNT_LOCATION

  message "Extracting stage3 tarball"
  command tar xpvf stage3-*.tar.xz --xattrs-include='*.*' --numeric-owner

  message "Copying configuration files"
  command mkdir -pv ${MOUNT_LOCATION}/etc
  command mkdir -pv ${MOUNT_LOCATION}/etc/portage


  message "Copying kernel configuration files"
  command cp -v $KERNEL_CONFIG_FILE ${MOUNT_LOCATION}/kernel-config

  # Chroot
  message "Copying DNS info"
  command cp --dereference /etc/resolv.conf ${MOUNT_LOCATION}/etc/

  message "Mounting Necessary Filesystems"
  command mount --types proc /proc /mnt/gentoo/proc
  command mount --rbind /sys /mnt/gentoo/sys
  command mount --make-rslave /mnt/gentoo/sys
  command mount --rbind /dev /mnt/gentoo/dev
  command mount --make-rslave /mnt/gentoo/dev

  message "Chrooting into System"
  command chroot $MOUNT_LOCATION /bin/bash -c "install_gentoo_chroot"
}

install_gentoo_chroot()
{
  message "Inside chroot env"
  command env-update
  command source /etc/profile
  command export PS1="(chroot) $PS1"

  # Portage
  message "Installing portage snapshot"
  command emerge-webrsync

  #command mkdir -vp /etc/portage/repos.conf
  #command cp -v /usr/share/portage/config/repos.conf /etc/portage/repos.conf/gentoo.conf

  # Set profile
  #message "Setting profile"
  #command eselect profile list
  #command eselect profile set default/linux/amd64/17.1

  message "Configuring /etc/portage/make.conf"
  cat << EOF > /etc/portage/make.conf
# Skye laptop make.conf

COMMON_FLAGS="-march=znver2 -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

PORTAGE_NICENESS=1
MAKEOPTS="-j6 -l6"
EMERGE_DEFAULT_MAKEOPTS="--jobs=6 --load-average=6"

FEATURES="parallel-install"
ACCEPT_KEYWORDS="~amd64"
VIDEO_CARDS="amdgpu"

USE="-suid -systemd X alsa pulseaudio elogind"

GRUB_PLATFORMS="efi-64"

GENTOO_MIRRORS="https://mirror.leaseweb.com/gentoo/"
EOF

  message "Updating @world set"
  command emerge --ask --update --deep --newuse --quiet @world

  message "Installing filesystem packages"
  command emerge --ask --quiet $PACKAGES

  message "Configuring timezone"
  command echo "$TIMEZONE" > /etc/timezone
  command emerge --config sys-libs/timezone-data

  message "Writing /etc/locale.gen file"
  cat << EOF > /etc/locale.gen
en_US.UTF-8 UTF-8
EOF

  command locale-gen
  command eselect locale set en_US.utf8

  message "Reloading Environment"
  command env-update && source /etc/profile && export PS1="(chroot) $PS1"

  message "Downloading Kernel Sources"
  command emerge --ask sys-kernel/gentoo-sources

  message "Cleaning Kernel source folder"
  command cd /usr/src/linux/
  
  message "Loading kernel configuration file"
  command mv -v /kernel-config /usr/src/linux/.config-gentoo-final
  command cp -v /usr/src/linux/.config-gentoo-final /usr/src/linux/.config

  message "Beginning Kernel Compilation Process"
  command make $MAKE_OPTIONS
  command make modules_install
  command make install

  message "Removing old kernel files"
  command rm -rf /boot/*old
  
  #message "Creating bootx64.efi, (Meant for UEFI systems)"
  #command mkdir -pv /boot/efi/boot
  #command cp /boot/vmlinuz-* /boot/efi/boot/bootx64.efi

  message "Installing genkernel"
  command emerge --ask sys-kernel/genkernel

  message "Generating initramfs"
  command genkernel --install --kernel-config="/usr/src/linux/.config-gentoo-final" initramfs

  cat << EOF > /etc/fstab
# /etc/fstab: static file system information.
#
# noatime turns off atimes for increased performance (atimes normally aren't
# needed); notail increases performance of ReiserFS (at the expense of storage
# efficiency).  It's safe to drop the noatime options if you want and to
# switch between notail / tail freely.
#
# The root filesystem should have a pass number of either 0 or 1.
# All other filesystems should have a pass number of 0 or greater than 1.
#
# See the manpage fstab(5) for more information.
#

# <fs>                  <mountpoint>    <type>          <opts>          <dump/pass>

# NOTE: If your BOOT partition is ReiserFS, add the notail option to opts.
${BOOT_PARTITION}               /boot           vfat            defaults  0 2
${SWAP_PARTITION}               none            swap            sw              0 0
${ROOT_PARTITION}               /               ext4           noatime            0 1
EOF

  message "Downloading firmware"
  command emerge --ask --autounmask-continue sys-kernel/linux-firmware
  
  message "Setting Hostname"
  command sed -i "s/localhost/$HOSTNAME/g" /etc/conf.d/hostname
  message "Creating /etc/conf.d/net"
  command touch /etc/conf.d/net
  message "Installing netifrc"
  command emerge --ask --noreplace net-misc/netifrc
  message "Setting network interfaces to activate at boot"
  command cd /etc/init.d
  command ln -s net.lo net.enp2s0
  command rc-update add net.enp2s0 default

  message "Configuring Bootloader"
  command emerge --ask sys-boot/grub:2
  message "Installing grub2"
  command grub-install --target=x86_64-efi --efi-directory=/boot/efi
  command grub-mkconfig -o /boot/grub/grub.cfg

  message "Testing setting a password from here, not sure if this works"
  command passwd

  message "Base installation has finished but there are still some steps that have to be done"
}

# Exporting necessary functions and variables
export -f install_gentoo_chroot
export -f message
export -f command

export LRED
export GREEN
export LCYAN
export LBLUE
export LPURPLE
export DGRAY
export NC

export PACKAGES
export TIMEZONE
export CFLAGS
export USE_FLAGS
export MAKE_OPTIONS
export BIOS_PARTITION
export BOOT_PARTITION
export SWAP_PARTITION
export ROOT_PARTITION
export ROOT_FS_TYPE
export MAKE_OPTIONS
export HOSTNAME

install_gentoo_prep

